In [1]:
import numpy as np
from scipy import spatial
import itertools
import math

In [13]:
# UNIT TESTING THIS CAN BE REMOVED
azimuth_recon_1, colatitude_recon_1 = math.pi, 0
azimuth_recon_2, colatitude_recon_2 = -math.pi, math.pi
centroid_1 = [0,0,0]
centroid_2 = [1,1,1]

In [14]:
tol = 3e-3
r1 = np.arange(0,0.5,tol)[:, np.newaxis] # or 0.25 depending on the radius
r2 = np.arange(0,0.5,tol)[:, np.newaxis]

In [15]:
spherical_1 = np.array([np.cos(azimuth_recon_1)*np.sin(colatitude_recon_1),np.sin(azimuth_recon_1)*np.sin(colatitude_recon_1),np.cos(colatitude_recon_1)])[:, np.newaxis]
spherical_2 = np.array([np.cos(azimuth_recon_2)*np.sin(colatitude_recon_2),np.sin(azimuth_recon_2)*np.sin(colatitude_recon_2),np.cos(colatitude_recon_2)])[:, np.newaxis]

estimate_1 = r1*spherical_1.T + np.array(centroid_1)[np.newaxis,:] 
estimate_2 = r2*spherical_2.T + np.array(centroid_2)[np.newaxis,:]

In [17]:
tree1 = spatial.KDTree(estimate_1)
tree2 = spatial.KDTree(estimate_2)

# Purpose: Find all pairs of points whose distance is at most r

# We have all the indicies for in tree2 that matches tree 1
indices = tree1.query_ball_tree(tree2, r = 3)

# Clean up all the empty arrays and fix the single brackets
sweep = list(itertools.chain.from_iterable(indices))

# Numerate the indices, so we can see where the two arrays match
temp1 = []
for index_a, index_b in enumerate(indices):
    if index_b != []:
        temp1.append(index_a)
temp2 = list(zip(blah,sweep))

# This checks if the indices from the data array are indeed correct
for j in range(len(temp2)):
    c1 = temp[j][0]
    c2 = temp[j][1]
    print(estimate_2[c1]) #, data2[c2]
    
    # if its truth
    #return estimate_1[c1], estimate_2[c2], True

[1. 1. 1.]
[1.    1.    0.997]
[1.    1.    0.994]
[1.    1.    0.991]
[1.    1.    0.988]
[1.    1.    0.985]
[1.    1.    0.982]
[1.    1.    0.979]
[1.    1.    0.976]
[1.    1.    0.973]
[1.   1.   0.97]
[1.    1.    0.967]
[1.    1.    0.964]
[1.    1.    0.961]
[1.    1.    0.958]
[1.    1.    0.955]
[1.    1.    0.952]
[1.    1.    0.949]
[1.    1.    0.946]
[1.    1.    0.943]
[1.   1.   0.94]
[1.    1.    0.937]
[1.    1.    0.934]
[1.    1.    0.931]
[1.    1.    0.928]
[1.    1.    0.925]
[1.    1.    0.922]
[1.    1.    0.919]
[1.    1.    0.916]
[1.    1.    0.913]
[1.   1.   0.91]
[1.    1.    0.907]
[1.    1.    0.904]
[1.    1.    0.901]
[1.    1.    0.898]
[1.    1.    0.895]
[1.    1.    0.892]
[1.    1.    0.889]
[1.    1.    0.886]
[1.    1.    0.883]
[1.   1.   0.88]
[1.    1.    0.877]
[1.    1.    0.874]
[1.    1.    0.871]
[1.    1.    0.868]
[1.    1.    0.865]
[1.    1.    0.862]
[1.    1.    0.859]
[1.    1.    0.856]
[1.    1.    0.853]
[1.   1.   0.85]
[1. 

### References

[Fastest way to find the closest point to a given point in 3D, in Python
](https://stackoverflow.com/questions/2641206/fastest-way-to-find-the-closest-point-to-a-given-point-in-3d-in-python?rq=1)

[KD TREE EXAMPLE WITH CUSTOM EUCLIDEAN DISTANCE BALL QUERY](http://code.activestate.com/recipes/578434-a-simple-kd-tree-example-with-custom-euclidean-dis/)

[Getting rid of double brackets](https://www.quora.com/How-can-I-convert-the-list-1-2-3-into-1-2-3-in-Python-Basically-I-want-the-list-to-be-flattened)

[Python/Scipy: KDTree Query Ball Point performance issue](https://stackoverflow.com/questions/43136142/python-scipy-kdtree-query-ball-point-performance-issue)

[Using k-d trees to efficiently calculate nearest neighbors in 3D vector space](https://blog.krum.io/k-d-trees/)

[scipy.spatial.KDTree](https://docs.scipy.org/doc/scipy-0.14.0/reference/generated/scipy.spatial.KDTree.html#scipy.spatial.KDTree)